language: pt_br
train:
  - filepath: /Users/periclesjr/Documents/Benchmark/bothub/benchmark/datafiles/Benchmark_Training.zip
  - filename: 'Benchmark_Training'
  - wit_token: 'Bearer OWL5XSVZVJNJS4BAVLVXV6STDU7SMPUF'
  - wit_version: 20180808
  - filetype: zip
tests:
  - text: O Real Madrid jogará hoje?
    expected:
      - intent: esporte
      - entities:
        - value: Real Madrid
          entity: time
  - text: Em que colocação está o Botafogo?
    expected:
      - intent: esporte
      - entities:
        - value: Botafogo
          entity: time
  - text: Quais partidas da rodada atual serão televisionadas?
    expected:
      - intent: esporte
  - text: Quantos gols o Barcelona fez no Liverpool?
    expected:
      - intent: esporte
      - entities:
        - value: Barcelona
          entity: time
        - value: Liverpool
          entity: time
  - text: Quem é o favorito do brasileirão?
    expected:
      - intent: esporte
      - entities:
        - value: brasileirão
          entity: competicao
  - text: Neymar está jogando em que time?
    expected:
      - intent: esporte
      - entities:
        - value: Neymar
          entity: nome
  - text: Qual time revelou o jogador Firmino?
    expected:
      - intent: esporte
      - entities:
        - value: Firmino
          entity: nome
  - text: Quando vai acontecer o próximo amistoso da seleção brasileira?
    expected:
      - intent: esporte
      - entities:
        - value: seleção brasileira
          entity: time
  - text: Quem foi o maior goleador da história?
    expected:
      - intent: esporte
  - text: Quem foi o melhor jogador do mundo Pelé ou Maradona?
    expected:
      - intent: esporte
      - entities:
        - value: Pelé
          entity: nome
        - value: Maradona
          entity: nome
  - text: Tem alguma lanchonete aberta?
    expected:
      - intent: comida
      - entities:
        - value: lanchonete
          entity: lugar
  - text: Qual o fastfood mais próximo da minha casa?
    expected:
      - intent: comida
      - entities:
        - value: fastfood
          entity: lugar
        - value: minha casa
          entity: lugar
  - text: Qual o cardápio do restaurante Divina's?
    expected:
      - intent: comida
      - entities: 
        - value: restaurante
          entity: lugar
        - value: Divina's
          entity: lugar
        - value: Divina's
          entity: marca
  - text: Onde posso comer hamburguer hoje?
    expected:
      - intent: comida
      - entities:
        - value: hamburguer
          entity: tipo_comida
  - text: Qual a cafeteria menos lotada na sexta feira?
    expected:
      - intent: comida
      - entities:
        - value: sexta feira
          entity: data
        - value: cafeteria
          entity: lugar
  - text: qual a faixa de preço do gbarbosa?
    expected:
      - intent: comida
      - entities:
        - value: gbarbosa
          entity: lugar
        - value: gbarbosa
          entity: marca
  - text: O Careca abre segunda de 19:00 horas?
    expected:
      - intent: comida
      - entities:
        - value: Careca
          entity: lugar
        - value: segunda
          entity: data
  - text: Quanto custa a pizza de frango?
    expected:
      - intent: comida
      - entities:
        - value: pizza de frango
          entity: tipo_comida
  - text: Quais os melhores rodizios da cidade?
    expected:
      - intent: comida
      - entities:
        - value: cidade
          entity: lugar
  - text: Qual o delivery de sushi mais próximo da minha residência?
    expected:
      - intent: comida
      - entities:
        - value: delivery
          entity: tipo_comida
        - value: sushi
          entity: tipo_comida
        - value: minha residência
          entity: lugar
  - text: Quais filmes de ação você me recomendaria?
    expected:
      - intent: cinema
      - entities:
        - value: ação
          entity: genero
        - value: filmes
          entity: tipo_de_programa
  - text: Quem está estrelando uma noite no museu?
    expected:
      - intent: cinema
      - entities:
        - value: uma noite no museu
          entity: tipo_de_programa
  - text: Quais os melhores documentários sobre astronomia?
    expected:
      - intent: cinema
      - entities:
        - value: documentários
          entity: tipo_de_programa
  - text: Você já assistiu todo mundo em pânico?
    expected:
      - intent: cinema
      - entities:
        - value: todo mundo em pânico
          entity: tipo_de_programa
  - text: Quais os clássicos de terror?
    expected:
      - intent: cinema
      - entities:
        - value: terror
          entity: genero
  - text: Quais os melhores filmes de steven spielberg?
    expected:
      - intent: cinema
      - entities:
        - value: steven spielberg
          entity: nome
  - text: Ainda existem locadoras de dvd?
    expected:
      - intent: cinema
      - entities:
        - value: locadoras
          entity: lugar
  - text: Atores mais cotados para fazer Jurasic Park?
    expected:
      - intent: cinema
      - entities:
        - value: Atores
          entity: profissao
        - value: Jurasic Park
          entity: tipo_de_programa
  - text: Brad pitt atuou em quantos filmes de drama?
    expected:
      - intent: cinema
      - entities:
        - value: Brad pitt
          entity: nome
        - value: drama
          entity: genero
  - text: Quando foi lançado desventuras em série?
    expected:
      - intent: cinema
      - entities:
        - value: desventuras em série
          entity: tipo_de_programa
  - text: Quantas pessoas nascem na indonésia a cada ano?
    expected:
      - intent: geografia
      - entities:
        - value: indonésia
          entity: lugar
        - value: ano
          entity: data
  - text: Qual o índice pluviométrico da carolina do norte?
    expected:
      - intent: geografia
      - entities:
        - value: carolina do norte
          entity: lugar
  - text: Quantos países fazem fronteira com o Cazaquistão?
    expected:
      - intent: geografia
      - entities:
        - value: Cazaquistão
          entity: lugar
  - text: Qual a cidade mais quente da Nigéria?
    expected:
      - intent: geografia
      - entities:
        - value: Nigéria
          entity: lugar
        - value: cidade
          entity: lugar
  - text: Qual pais com maior volume populacional do mundo?
    expected:
      - intent: geografia
  - text: Qual é a área do Congo?
    expected:
      - intent: geografia
      - entities:
        - value: Congo
          entity: Lugar
  - text: Vai chover hoje?
    expected:
      - intent: geografia
  - text: Quantas pessoas vivem hoje em Alagoas?
    expected:
      - intent: geografia
      - entities:
        - value: Alagoas
          entity: Lugar
  - text: Qual a taxa de desemprego no Brasil?
    expected:
      - intent: geografia
      - entities:
        - value: Brasil
          entity: Lugar
  - text: Quantos continentes existem no planeta?
    expected:
      - intent: geografia
      - entities:
        - value: continentes
          entity: lugar
  - text: Preciso encontrar um bom psicólogo
    expected:
      - intent: saude
      - entities:
        - value: psicólogo
          entity: profissao
  - text: Qual médico eu deveria consultar para examinar os meus olhos?
    expected:
      - intent: saude
      - entities:
        - value: olhos
          entity: parte_do_corpo
        - value: médico
          entity: profissao
  - text: Estou sentindo uma forte dor nas costas o que devo fazer?
    expected:
      - intent: saude
      - entities:
        - value: dor nas costas
          entity: patologia
        - value: costas
          entity: parte_do_corpo
  - text: Contraí uma gripe pesada devo tomar vitamina C?
    expected:
      - intent: saude
      - entities:
        - value: gripe
          entity: patologia
  - text: Meu filho está engasgado como devo proceder?
    expected:
      - intent: saude
      - entities:
        - value: engasgado
          entity: patologia
  - text: Me feri com uma tesoura posso contrair tétano?
    expected:
      - intent: saude
      - entities:
        - value: tétano
          entity: patologia
  - text: Preciso me vacinar contra gripe.
    expected:
      - intent: saude
  - text: Onde fica o posto de saúde mais próximo?
    expected:
      - intent: saude
      - entities:
        - value: posto de saúde
          entity: lugar
  - text: Existe alguma clínica 24h na minha cidade?
    expected:
      - intent: saude
      - entities:
        - value: cidade
          entity: lugar
        - value: clínica
          entity: lugar
  - text: Como posso descobrir se estou diabético?
    expected:
      - intent: saude
      - entities:
        - value: diabético
          entity: patologia
  - text: Eu posso pagar em uma lotérica?
    expected:
      - intent: financeiro
      - entities:
        - value: lotérica
          entity: lugar
  - text: Posso pagar o boleto após o vencimento?
    expected:
      - intent: financeiro
      - entities:
        - value: após o vencimento
          entity: data
  - text: Posso fazer adiantamento do valor devido?
    expected:
      - intent: financeiro
  - text: tem problema em efetuar o pagamento amanhã?
    expected:
      - intent: financeiro
      - entities:
        - value: amanhã
          entity: data
  - text: É possível atualizar a data de vencimento?
    expected:
      - intent: financeiro
      - entities:
        - value: data de vencimento
          entity: data
  - text: Eu gostaria de cancelar a minha compra
    expected:
      - intent: financeiro
  - text: Você poderia estornar a diferença da minha compra?
    expected:
      - intent: financeiro
  - text: Existe a possibilidade de financiar o restante da dívida?
    expected:
      - intent: financeiro
  - text: Eu já paguei
    expected:
      - intent: financeiro
  - text: Não quero mais receber essas cobranças
    expected:
      - intent: financeiro
  - text: Tô querendo moto modelo mais novo
    expected:
      - intent: automoveis
      - entities:
        - value: moto
          entity: veiculo
  - text: Compro ou troco carro usado
    expected:
      - intent: automoveis
      - entities:
        - value: carro
          entity: veiculo
  - text: Vende-se moto honda 150
    expected:
      - intent: automoveis
      - entities:
        - value: honda 150
          entity: modelo_moto
        - value: honda
          entity: marca
  - text: Quando sai o novo lançamento do FIAT
    expected:
      - intent: automoveis
      - entities:
        - value: FIAT
          entity: marca
  - text: Quero fazer manutenção no meu automóvel
    expected:
      - intent: automoveis
  - text: Troco carro uno 98 por moto
    expected:
      - intent: automoveis
      - entities:
        - value: uno
          entity: modelo_carro
  - text: Economizei para trocar de carro esse ano
    expected:
      - intent: automoveis
      - entities:
        - value: esse ano
          entity: data
  - text: Compro carro que não seja caro
    expected:
      - intent: automoveis
  - text: Quero comprar o modelo atual do Civic
    expected:
      - intent: automoveis
      - entities:
        - value: Civic
          entity: marca
  - text: Estou interessado na CB300
    expected:
      - intent: automoveis
      - entities:
        - value: CB300
          entity: modelo_moto
  - text: Como faço pra votar?
    expected:
      - intent: politica
  - text: Posso escolher mais de um presidente?
    expected:
      - intent: politica
      - entities:
        - value: presidente
          entity: cargo_politico
  - text: Tenho dúvida quanto ao canditado Péricles
    expected:
      - intent: politica
      - entities:
        - value: Péricles
          entity: nome
  - text: O candidato 15 é ladrão
    expected:
      - intent: politica
  - text: Vou votar em ninguém esse ano
    expected:
      - intent: politica
      - entities:
        - value: ano
          entity: data
  - text: Meu voto será pro 51
    expected:
      - intent: politica
  - text: Prefiro o Partido Roxo
    expected:
      - intent: politica
      - entities:
        - value: Roxo
          entity: cor
  - text: Canditado 51 é ladrão vou votar no 15
    expected:
      - intent: politica
  - text: Qual o político menos ladrão pra votar?
    expected:
      - intent: politica
  - text: Peter para presidente do Brasil
    expected:
      - intent: politica
      - entities:
        - value: Peter
          entity: nome
        - value: Brasil
          entity: lugar
  - text: Tô afim de começar um jogo novo
    expected:
      - intent: games
  - text: Tô com task vou jogar só amanhã
    expected:
      - intent: games
      - entities:
        - value: amanhã
          entity: data
  - text: Posso jogar com vocês?
    expected:
      - intent: games
  - text: Esse game pega Multiplayer
    expected:
      - intent: games
      - entities:
        - value: Multiplayer
          entity: tipo_jogo
  - text: Dá pra logar no PUBG?
    expected:
      - intent: games
      - entities:
        - value: PUBG
          entity: titulo_jogo
  - text: Tô esperando você ficar online pra gente jogar
    expected:
      - intent: games
  - text: Qual o seu game favorito?
    expected:
      - intent: games
  - text: No PC eu uso a Steam
    expected:
      - intent: games
      - entities:
        - value: Steam
          entity: marca
  - text: Já jogou algum jogo da Blizzard?
    expected:
      - intent: games
      - entities:
        - value: Blizzard
          entity: marca
  - text: Gosto de jogar Minecraft no celular
    expected:
      - intent: games
      - entities:
        - value: Minecraft
          entity: titulo_jogo
  - text: Como tratar as pulgas do meu Javalí?
    expected:
      - intent: pets
      - entities:
        - value: Javalí
          entity: animal
        - value: pulgas
          entity: patologia
        - value: pulgas
          entity: animal
  - text: Meus cachorros não se dão bem
    expected:
      - intent: pets
      - entities:
        - value: cachorros
          entity: animal
  - text: Minha gata está vomitando muitas bolas de pelo
    expected:
      - intent: pets
      - entities:
        - value: vomitando
          entity: patologia
        - value: gata
          entity: animal
  - text: Meu cachorro não está muito bem de saúde
    expected:
      - intent: pets
      - entities:
        - value: cachorro
          entity: animal
  - text: Estou criando um novo filhote de urso
    expected:
      - intent: pets
      - entities:
        - value: urso
          entity: animal
  - text: Meu porco de estimação está com pulgas
    expected:
      - intent: pets
      - entities:
        - value: porco
          entity: animal
  - text: Meus pets latem muito como resolver?
    expected:
      - intent: pets
  - text: Quanto tempo vive um gato egípcio?
    expected:
      - intent: pets
  - text: tenho muitos pets como cuidar de todos?
    expected:
      - intent: pets
  - text: posso criar um cachorro em apartamento?
    expected:
      - intent: pets
      - entities:
        - value: apartamento
          entity: lugar